services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/dynamic_targets.json:/etc/prometheus/dynamic_targets.json
      - ./config/rules/alert_rules.yml:/etc/prometheus/rules/alert_rules.yml
      - ./config/rules/recording_rules.yml:/etc/prometheus/rules/recording_rules.yml

  promLens:
    image: prom/promlens
    ports:
      - 8080:8080

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./config/alert-manager/alertmanager.yml:/etc/alertmanager/alertmanager.yml

  consul-server:
    image: hashicorp/consul:1.11.2
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp

  consul-exporter:
    image: prom/consul-exporter
    ports:
      - 9107:9107
    command: --consul.server=consul-server:8500