services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./config/dynamic_targets.json:/etc/prometheus/dynamic_targets.json
      - ./config/rules:/etc/prometheus/rules