global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "web-server-1"
    static_configs:
      - targets: ["web-server-1:8080"]
  - job_name: "web-server-2"
    static_configs:
      - targets: ["web-server-1:9090"]
  - job_name: "dynamic-web-servers"
    static_configs:
      file_sd_configs:
        - files:
          - /etc/prometheus/targets.json