receivers:
  - name: "slack-noti"
    slack_configs:
      - send_resolved: true
        username: 'alertmanager'
        channel: '#prometheus-noti'
        api_url: 'https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX'

route:
  receiver: 'slack-noti'
  group_by: ['severity']
  routes:
  - receiver: 'slack-noti'
    group_wait: 10s
    group_interval: 5m
    repeat_interval: 3h
    match:
      severity: critical

